[phases.setup]
nixPkgs = ["nodejs_23", "npm-10_x"]
aptPkgs = ["openssl", "curl", "wget"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]
nixPkgs = ["nodejs_23", "npm-10_x"]

[phases.build]
cmds = ["npm run build"]
nixPkgs = ["nodejs_23"]

[start]
cmd = "npm run start"